CREATE TYPE "public"."alalay_guidance_action_type" AS ENUM('Solution', 'Penalty');--> statement-breakpoint
CREATE TYPE "public"."alalay_offense_type" AS ENUM('Minor Offense', 'Major Offense');--> statement-breakpoint
CREATE TYPE "public"."alalay_role_shortcut" AS ENUM('@admin', '@edu', '@conci');--> statement-breakpoint
CREATE TYPE "public"."alalay_user_role" AS ENUM('ADMIN', 'TEACHER', 'COUNCILOR');--> statement-breakpoint
CREATE TYPE "public"."alalay_user_status" AS ENUM('ACTIVE', 'DISABLED', 'DROPOUT');--> statement-breakpoint
CREATE TABLE "alalay_section_subject" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alalay_section_subject_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sectionId" varchar(64) NOT NULL,
	"subjectCode" varchar(64) NOT NULL,
	"subjectName" varchar(160) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_section" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"program" varchar(32) NOT NULL,
	"yearLevel" varchar(32) NOT NULL,
	"block" varchar(8),
	"teacherId" varchar(64),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_student_family_background" (
	"studentId" varchar(64) PRIMARY KEY NOT NULL,
	"motherName" varchar(160),
	"motherAge" integer,
	"motherOccupation" varchar(160),
	"fatherName" varchar(160),
	"fatherAge" integer,
	"fatherOccupation" varchar(160),
	"parentsMarried" boolean,
	"parentsSeparated" boolean,
	"parentsNotMarried" boolean,
	"motherFatherRemarried" varchar(160),
	"stepParentOrGuardianName" varchar(160),
	"stepParentOrGuardianAge" integer,
	"stepParentOrGuardianOccupation" varchar(160),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_student_guidance_log" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"studentId" varchar(64) NOT NULL,
	"guidanceTime" varchar(8),
	"actionType" "alalay_guidance_action_type",
	"actionDetail" text,
	"offenseType" "alalay_offense_type",
	"entry" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_student_subject_grade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alalay_student_subject_grade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"studentId" varchar(64) NOT NULL,
	"sectionSubjectId" integer NOT NULL,
	"prelim" numeric(5, 2),
	"midterm" numeric(5, 2),
	"finals" numeric(5, 2),
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_student" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"studentNumber" varchar(64) NOT NULL,
	"fullName" varchar(160) NOT NULL,
	"imageUrl" text,
	"status" "alalay_user_status" DEFAULT 'ACTIVE' NOT NULL,
	"age" integer,
	"guardian" varchar(160),
	"contact" varchar(64),
	"program" varchar(32) NOT NULL,
	"yearLevel" varchar(32) NOT NULL,
	"birthDate" date,
	"birthPlace" varchar(160),
	"address" text,
	"telCellNo" varchar(64),
	"yearSectionText" varchar(64),
	"sex" varchar(16),
	"boardingHouse" text,
	"landlordOrLandlady" varchar(160),
	"previousSchoolAttended" varchar(160),
	"outstandingActivitiesHonorsAwards" text,
	"teacherId" varchar(64),
	"sectionId" varchar(64),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_system_log" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"actor" "alalay_role_shortcut" NOT NULL,
	"action" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alalay_teacher_section_subject" (
	"teacherId" varchar(64) NOT NULL,
	"sectionSubjectId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "teacher_section_subject_pk" PRIMARY KEY("teacherId","sectionSubjectId")
);
--> statement-breakpoint
CREATE TABLE "alalay_user" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"fullName" varchar(160) NOT NULL,
	"username" varchar(160) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" "alalay_user_role" NOT NULL,
	"shortcut" "alalay_role_shortcut" NOT NULL,
	"status" "alalay_user_status" DEFAULT 'ACTIVE' NOT NULL,
	"assignedSubjectCodes" text[] DEFAULT '{}' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "alalay_section_subject" ADD CONSTRAINT "alalay_section_subject_sectionId_alalay_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."alalay_section"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_section" ADD CONSTRAINT "alalay_section_teacherId_alalay_user_id_fk" FOREIGN KEY ("teacherId") REFERENCES "public"."alalay_user"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student_family_background" ADD CONSTRAINT "alalay_student_family_background_studentId_alalay_student_id_fk" FOREIGN KEY ("studentId") REFERENCES "public"."alalay_student"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student_guidance_log" ADD CONSTRAINT "alalay_student_guidance_log_studentId_alalay_student_id_fk" FOREIGN KEY ("studentId") REFERENCES "public"."alalay_student"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student_subject_grade" ADD CONSTRAINT "alalay_student_subject_grade_studentId_alalay_student_id_fk" FOREIGN KEY ("studentId") REFERENCES "public"."alalay_student"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student_subject_grade" ADD CONSTRAINT "alalay_student_subject_grade_sectionSubjectId_alalay_section_subject_id_fk" FOREIGN KEY ("sectionSubjectId") REFERENCES "public"."alalay_section_subject"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student" ADD CONSTRAINT "alalay_student_teacherId_alalay_user_id_fk" FOREIGN KEY ("teacherId") REFERENCES "public"."alalay_user"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_student" ADD CONSTRAINT "alalay_student_sectionId_alalay_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."alalay_section"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_teacher_section_subject" ADD CONSTRAINT "alalay_teacher_section_subject_teacherId_alalay_user_id_fk" FOREIGN KEY ("teacherId") REFERENCES "public"."alalay_user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "alalay_teacher_section_subject" ADD CONSTRAINT "alalay_teacher_section_subject_sectionSubjectId_alalay_section_subject_id_fk" FOREIGN KEY ("sectionSubjectId") REFERENCES "public"."alalay_section_subject"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "section_subject_unique_idx" ON "alalay_section_subject" USING btree ("sectionId","subjectCode");--> statement-breakpoint
CREATE INDEX "section_subject_section_idx" ON "alalay_section_subject" USING btree ("sectionId");--> statement-breakpoint
CREATE UNIQUE INDEX "section_name_unique_idx" ON "alalay_section" USING btree ("name");--> statement-breakpoint
CREATE INDEX "section_teacher_idx" ON "alalay_section" USING btree ("teacherId");--> statement-breakpoint
CREATE INDEX "student_family_student_idx" ON "alalay_student_family_background" USING btree ("studentId");--> statement-breakpoint
CREATE INDEX "student_guidance_student_idx" ON "alalay_student_guidance_log" USING btree ("studentId");--> statement-breakpoint
CREATE UNIQUE INDEX "student_subject_grade_unique_idx" ON "alalay_student_subject_grade" USING btree ("studentId","sectionSubjectId");--> statement-breakpoint
CREATE INDEX "student_grade_student_idx" ON "alalay_student_subject_grade" USING btree ("studentId");--> statement-breakpoint
CREATE UNIQUE INDEX "student_number_unique_idx" ON "alalay_student" USING btree ("studentNumber");--> statement-breakpoint
CREATE INDEX "student_section_idx" ON "alalay_student" USING btree ("sectionId");--> statement-breakpoint
CREATE INDEX "student_teacher_idx" ON "alalay_student" USING btree ("teacherId");--> statement-breakpoint
CREATE INDEX "student_status_idx" ON "alalay_student" USING btree ("status");--> statement-breakpoint
CREATE INDEX "system_log_created_idx" ON "alalay_system_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "teacher_section_subject_teacher_idx" ON "alalay_teacher_section_subject" USING btree ("teacherId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_username_unique_idx" ON "alalay_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_role_idx" ON "alalay_user" USING btree ("role");